version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: '-Dorg.gradle.parallel=false -Dorg.gradle.daemon=false'
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew testSandboxDebug
      - store_test_results:
          path: app/build/test-results
      - deploy:
          name: Deploy APK
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploy to Crashlytics (sandbox)"
              ./gradlew clean assembleSandboxDebug crashlyticsUploadDistributionSandboxDebug
            elif [[ "${CIRCLE_BRANCH}" =~ ^release.*$ ]]; then
              echo "Deploy to Crashlytics (production)"
              ./gradlew clean assembleProductionDebug crashlyticsUploadDistributionProductionDebug
              ./gradlew clean assembleBeta crashlyticsUploadDistributionBeta
            elif [[ "${CIRCLE_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Deploy to Google Play"
              ./gradlew clean assembleProductionRelease publishApkProductionRelease
            fi
      - store_artifacts:
          path: app/build/outputs
          destination: outputs

# TODO workaround for tag trigger
deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"